# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import funboost.assist.grpc_helper.funboost_grpc_pb2 as funboost__grpc__pb2


class FunboostBrokerServiceStub(object):
    """定义服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/funboost_grpc.FunboostBrokerService/Call',
                request_serializer=funboost__grpc__pb2.FunboostGrpcRequest.SerializeToString,
                response_deserializer=funboost__grpc__pb2.FunboostGrpcResponse.FromString,
                )


class FunboostBrokerServiceServicer(object):
    """定义服务
    """

    def Call(self, request, context):
        """简单的问候方法
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FunboostBrokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=funboost__grpc__pb2.FunboostGrpcRequest.FromString,
                    response_serializer=funboost__grpc__pb2.FunboostGrpcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'funboost_grpc.FunboostBrokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FunboostBrokerService(object):
    """定义服务
    """

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/funboost_grpc.FunboostBrokerService/Call',
            funboost__grpc__pb2.FunboostGrpcRequest.SerializeToString,
            funboost__grpc__pb2.FunboostGrpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
