# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: funboost_grpc.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66unboost_grpc.proto\x12\rfunboost_grpc\":\n\x13\x46unboostGrpcRequest\x12\x10\n\x08json_req\x18\x01 \x01(\t\x12\x11\n\tcall_type\x18\x02 \x01(\t\")\n\x14\x46unboostGrpcResponse\x12\x11\n\tjson_resp\x18\x01 \x01(\t2h\n\x15\x46unboostBrokerService\x12O\n\x04\x43\x61ll\x12\".funboost_grpc.FunboostGrpcRequest\x1a#.funboost_grpc.FunboostGrpcResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'funboost_grpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FUNBOOSTGRPCREQUEST']._serialized_start=38
  _globals['_FUNBOOSTGRPCREQUEST']._serialized_end=96
  _globals['_FUNBOOSTGRPCRESPONSE']._serialized_start=98
  _globals['_FUNBOOSTGRPCRESPONSE']._serialized_end=139
  _globals['_FUNBOOSTBROKERSERVICE']._serialized_start=141
  _globals['_FUNBOOSTBROKERSERVICE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
